# Generated by Django 4.2 on 2024-08-12 09:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonFightGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('player1_pokemon', models.CharField(max_length=50)),
                ('player2_pokemon', models.CharField(max_length=50)),
                ('battle_status', models.SmallIntegerField(blank=True, choices=[(1, 'BATTLE_INPROGRESS'), (2, 'BATTLE_COMPLETED'), (3, 'BATTLE_FAILED')], null=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('margin', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
